/*
 * AboutDialog.java
 *
 * Palo Open Office Calc AddIn
 * Copyright (C) 2008 PalOOCa Team,  Tensegrity Software GmbH, 2009

 * The software is licensed under an Open-Source License (GPL).
 * If you want to redistribute the software you must observe the regulations of
 * the GPL . If you want to redistribute the software without the
 * restrictions of the GPL, you have to contact Tensegrity Software GmbH
 * (Tensegrity) for written consent to do so.
 * Tensegrity may offer commercial licenses for redistribution (Dual Licensing)
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Created on 28. August 2007, 13:35
 *
 */

package org.palooca.dialogs;

import java.io.IOException;

/**
 *
 * @author  Andreas Schneider
 */
public class AboutDialog extends javax.swing.JFrame {
    
    private static AboutDialog instance;
    
    public static AboutDialog getInstance() {
        if (instance == null)
            instance = new AboutDialog();
        return instance;
    }
    
    /** Creates new form AboutDialog */
    private AboutDialog() {
        initComponents();
        this.setLocationRelativeTo(null); //center dialog on screen
    }

    private boolean isWindows() {
        String os = System.getProperty("os.name");
        if (os != null && os.startsWith("Windows"))
            return true;
        return false;
    }

    private boolean isOSX() {
        String os = System.getProperty("os.name");
        // System.out.println(os);
        if (os != null && os.startsWith("Mac OS X"))
            return true;
        return false;
    }

    private void startBrowserFallBack(String url) {
        if (isWindows()) {
            // cmd = 'rundll32 url.dll,FileProtocolHandler http://...'
            try {
                String cmd = "rundll32" + " " + "url.dll,FileProtocolHandler"
                        + " " + url;
                Process p = Runtime.getRuntime().exec(cmd);
            } catch (IOException e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
            }
        } else if (isOSX()) {
            try {
                String cmd = "open -a /Applications/Safari.app" + " " + url;
                Process p = Runtime.getRuntime().exec(cmd);
            } catch (IOException e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
            }
        }
    }

    private void startBrowser(String url)
    {
        if( !java.awt.Desktop.isDesktopSupported() ) {
            startBrowserFallBack(url);
            return;
        }

        java.awt.Desktop desktop = java.awt.Desktop.getDesktop();

        if( !desktop.isSupported( java.awt.Desktop.Action.BROWSE ) ) {
            startBrowserFallBack(url);
            return;
        }


        try {

            java.net.URI uri = new java.net.URI(url);
            desktop.browse( uri );
        }
        catch ( Exception e ) {
            startBrowserFallBack(url);
            return;
        }

        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCaption = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnWebsite = new javax.swing.JButton();
        btnRepo = new javax.swing.JButton();

        setTitle("About PalOOCa");
        setMinimumSize(new java.awt.Dimension(0, 350));
        setName("AboutDialog"); // NOI18N
        setResizable(false);

        lblCaption.setFont(new java.awt.Font("Tahoma", 1, 24));
        lblCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaption.setText("Palo for OpenOffice"); // NOI18N
        lblCaption.setFocusTraversalPolicyProvider(true);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Licence: LGPL 2.0 or later"); // NOI18N

        btnClose.setText("Close");
        btnClose.setActionCommand("CloseForm");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel6.setText("<html> Palo for OpenOffice is an OpenOffice.org Extension to allow Calc to communicate with <i>Jedox</i>' PALO Server. It has been originally been developed at the Chemnitz University of Technology, then was further developed by Tensegrity Software. Based on a fork of version 2.0.3 this release is maintained by Proclos.<br> Palo for OpenOffice is licensed under GPL terms. A copy of the license text should be available with the sourcecode which can be obtained from the source code repository. </html>"); // NOI18N

        btnWebsite.setText("Visit Website");
        btnWebsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebsiteActionPerformed(evt);
            }
        });

        btnRepo.setText("Visit Repository");
        btnRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepoActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .add(lblCaption, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(btnRepo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btnWebsite)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnClose))
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lblCaption)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 242, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnWebsite)
                    .add(btnClose)
                    .add(btnRepo))
                .addContainerGap())
        );

        jLabel6.getAccessibleContext().setAccessibleName("<html> Palo for OpenOffice is an OpenOffice.org Extension to allow Calc to communicate with <i>Jedox</i>' PALO Server. It has been originally been developed at the Chemnitz University of Technology, then was further developed by Tensegrity Software. Based on a fork of version 2.0.3 this release is maintained by proclos.<br> Palo for OpenOffice is licensed under GPL terms. A copy of the license text should be available with the sourcecode which can be obtained from the subversion repository. </html>");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWebsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebsiteActionPerformed
        startBrowser("http://palooca.sourceforge.net");
    }//GEN-LAST:event_btnWebsiteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepoActionPerformed
        startBrowser("http://hg.proclos.com/paloo");
    }//GEN-LAST:event_btnRepoActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRepo;
    private javax.swing.JButton btnWebsite;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCaption;
    // End of variables declaration//GEN-END:variables
    
}
